### ISSUE TITLE
고령친화도시 국제네트워크

### ISSUE THREAD

**Issue by Namsu88** [pwjdgus/Age_Friendly_City#102]
고령친화도시 국제네트워크의 가입 여부를 지방자치단체 별로 분류하여 그래프로도 표현하려고 합니다.
이 파일을 [지방자치단체별 고령친화도시 정책 및 현황.md](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EC%A7%80%EB%B0%A9%EC%9E%90%EC%B9%98%EB%8B%A8%EC%B2%B4%EB%B3%84%20%EA%B3%A0%EB%A0%B9%EC%B9%9C%ED%99%94%EB%8F%84%EC%8B%9C%20%EC%A0%95%EC%B1%85%20%EB%B0%8F%20%ED%98%84%ED%99%A9.md), [고령친화도시국제네트워크.md](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EA%B3%A0%EB%A0%B9%EC%B9%9C%ED%99%94%EB%8F%84%EC%8B%9C%EA%B5%AD%EC%A0%9C%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.md)
위의 두가지 파일 중 어느파일에 추가해야 적절한지 의견 부탁드립니다.

**Comment by merjunemong** [comment]
고령친화도시국제네트워크라는 주제 안에서 지방자치단체 별 가입 여부를 표현하는 거라 보면 후자가 더 표현하기도 좋고 적절하다고 생각합니다.

**Comment by Namsu88** [comment]
의견 반영해서 작성해보았습니다. 

[고령친화도시국제네트워크.md](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EA%B3%A0%EB%A0%B9%EC%B9%9C%ED%99%94%EB%8F%84%EC%8B%9C%EA%B5%AD%EC%A0%9C%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.md)
