### ISSUE TITLE
저장소 구축 준비

### ISSUE THREAD

**Issue by klavna** [pwjdgus/Age_Friendly_City#113]
여러 사람이 사용할 수 있는 고령 친화도시 데이터를 만든는 목표를 가지고 있으므로 데이터베이스 구축을 준비 했으면 좋겠습니다.
 학기중에 데이터 베이스를 구축까지는 못하더라도 설계하고 준비하면 깃 허브에도 더 체계적으로 정리 할수 있어서 좋은 결과가 있을 것 같습니다.

**Comment by pwjdgus** [comment]
👍👍

**Comment by wlwhsxz** [comment]
다른 참여자들도 볼 수 있도록 당분간 open issue 로 남겨두면 좋을 듯 합니다.
