### ISSUE TITLE
.md파일이 많아 보기에 난잡해보입니다.

### ISSUE THREAD

**Issue by Roniebin** [pwjdgus/Age_Friendly_City#115]
파일을 추가로 생성해 깔끔하게 만드는게 좋을것같습니다.

**Comment by klavna** [comment]
파일 분류를 잘해서 정리하면 확실히 보기 좋을 것 같습니다.

**Comment by pwjdgus** [comment]
이전부터 요청 했던 내용이지만 잘 지켜지지 않네요..

**Comment by wlwhsxz** [comment]
@Roniebin @klavna 현재는 분류가 잘 진행된 것 같나요?

**Comment by Roniebin** [comment]
@wlwhsxz 분류 잘 진행된것 같습니다. 따라서 이전에 비해 더 읽기쉽고 자료찾기가 수월해진것같습니다.

**Comment by wlwhsxz** [comment]
@Roniebin 감사합니다 =] 
해당 이슈 close 하도록 하겠습니다.
