### ISSUE TITLE
고령친화 도시 설계를 위한 자료들에 고령친화 식품 정보는 관계가 없다고 생각합니다.

### ISSUE THREAD

**Issue by Telettubi** [pwjdgus/Age_Friendly_City#122]
고령친화 도시 설계를 위해 필요한 정보들을 모으는 저장소에 
고령친화 식품에 대한 정보는 필요하지 않다고 생각합니다.

**Comment by hjun0325** [comment]
고령친화도시는 노인이 건강하고 활력있는 사회생활을 영위할 수 있도록 정책 및 인프라, 서비스 등이 조성된 도시를 말합니다.
그래서 저는 고령친화식품은 노인들의 건강을 위한 서비스부분에 해당한다고 생각해서 추가했습니다.
