### ISSUE TITLE
README.md '수집현황' 단어 변경 제안

### ISSUE THREAD

**Issue by merjunemong** [pwjdgus/Age_Friendly_City#141]
README.md의 두번째 헤더인 "수집현황"이란 단어를 "고령친화의 개념"같은 다른 단어로 바꾸는 것이 더 적절할 것 같은데 최적의 단어가 무엇일지 참여자분들의 의견을 묻고 싶습니다.

**Comment by sj2305** [comment]
'조사현황'은 어떨까요?

**Comment by merjunemong** [comment]
"고령친화적인 지역 사회 개발을 위한 주요 전략"같은 다른 내용은 다 따로 헤더가 있는데 고령친화의 개념이나 필요성 같은 내용들은 헤더 없이 바로 내용이 있어서 제가 좀 햇갈렸던 거 같습니다. "수집현황"을 바꾼다기보단 "고령친화의 개념"같은 헤더를 하나 더 추가하고 싶다는 뜻으로 정정하겠습니다.
