### ISSUE TITLE
데이터 파일 저장소 위치 변경제안

### ISSUE THREAD

**Issue by klavna** [pwjdgus/Age_Friendly_City#145]
데이터 파일 저장소도 수집 자료의 일부인 것 같은데,  수집 자료 내부로 옮기는 것이 좋을 것 같습니다.

**Comment by merjunemong** [comment]
데이터 파일에 있는 내용만 따로 노는 느낌이 들어서 수집 자료 내부로 옮기는 것에 찬성합니다
