### ISSUE TITLE
일부 문장 형식 변형 제안

### ISSUE THREAD

**Issue by 0406ckh** [pwjdgus/Age_Friendly_City#146]
[참고자료 : 고령친화도시 및 커뮤니티 개발: 전 세계 사례 연구] 형식으로 적혀있는 부분들을
[고령친화도시 및 커뮤니티 개발: 전 세계 사례 연구(참고자료)]로 바꾸는 것이 보는데 더 나을 것 같습니다.

**Comment by wlwhsxz** [comment]
해당 건 완료하여 close 하겠습니다.
