### ISSUE TITLE
논문 폴더를 새로 만들었습니다.

### ISSUE THREAD

**Issue by JeMinMoon** [pwjdgus/Age_Friendly_City#154]
자료들을 찾을 때 참고했던 논문들도 따로 한 곳에 모아야될 필요가 있어보여 논문폴더를 만들었습니다. 기존에는 자료밑에 참고 링크만 달았는데 논문명과 대략적인 설명이 있어가 나중에 찾아보기 편할 것 같습니다. 참고하시고 본인이 수집한 자료와 관련된 논문들을 추가해주세요.

**Comment by klavna** [comment]
논문 폴더도 수집자료 안에 위치하는게 좋지 않을 까요?

**Comment by JeMinMoon** [comment]
따로 보기 편하려고 빼놓긴 했는데 어디에 있든 상관은 없어보입니다.
