### ISSUE TITLE
지방자치단체 정책 및 현황 자료 추가

### ISSUE THREAD

**Issue by qpwery** [pwjdgus/Age_Friendly_City#158]
지방자치단체별 고령친화도시 정책 및 현황.md의 **경기도** 정책 및 현황에 알맞은 자료를 찾았습니다.

[경기도 고령친화도시 조성 지원계획 연구.pdf](https://github.com/pwjdgus/Age_Friendly_City/files/8487058/default.pdf)

**Comment by wlwhsxz** [comment]
@qpwery 해당 자료 main 폴더로 업로드 되었나요?
