### ISSUE TITLE
고령친화도시 설계를 위한 노인인구 비율 파악

### ISSUE THREAD

**Issue by qpwery** [pwjdgus/Age_Friendly_City#159]
고령친화도시를 효율적으로 설계하기 위해서는 각 지역의 노인인구 비율을 파악해야 합니다.
지역별 인구이동을 고려한 노인인구 비율을 파악하고, 이를 토대로 고령친화도시를 설계하는 것이 효과적일 것 같습니다.

[지역별 인구이동이 고령화에 미치는 영향.pdf](https://github.com/pwjdgus/Age_Friendly_City/files/8487096/default.pdf)

**Comment by wlwhsxz** [comment]
@qpwery 업로드 된 파일일까요?
