### ISSUE TITLE
해외 사례 중복 내용 관련

### ISSUE THREAD

**Issue by rolling1231** [pwjdgus/Age_Friendly_City#160]
해외 사례에서 캐나다 캘거리가 중복되고 있는데, 이를 따로 분리하여 작성한 이유가 무엇인지 궁금합니다.
여기에 더해서 [해외 사례](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EC%82%AC%EB%A1%80/%ED%95%B4%EC%99%B8%EC%82%AC%EB%A1%80/%ED%95%B4%EC%99%B8%EC%82%AC%EB%A1%80.md)와 [해외 고령친화도시 모델](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EC%82%AC%EB%A1%80/%ED%95%B4%EC%99%B8%EC%82%AC%EB%A1%80/%ED%95%B4%EC%99%B8%20%EA%B3%A0%EB%A0%B9%EC%B9%9C%ED%99%94%EB%8F%84%EC%8B%9C%20%EB%AA%A8%EB%8D%B8.md)
 각각의 md파일을 분리한 이유 또한 궁금합니다.

**Comment by wlwhsxz** [comment]
@sangyong-99 @Roniebin

**Comment by Roniebin** [comment]
제가 중복내용이 있는지 미처 모르고 추가하였습니다. 수정하겠습니다.!

**Comment by wlwhsxz** [comment]
@Roniebin 감사합니다. 수정하시고 commit 시에 설명란에 #번호 남겨주시면 확인에 용이할 듯 합니다 ^^
