### ISSUE TITLE
체크리스트 링크 수정 요청

### ISSUE THREAD

**Issue by merjunemong** [pwjdgus/Age_Friendly_City#168]
@JeMinMoon WHO 고령친화도시 가이드 및 체크리스트.md 에 있는 체크리스트 링크가 JeMinMoon-patch-2 branch에 있는 체크리스트로 걸려 있는데 Main에 있는 체크리스트로 링크를 바꾸는게 나을 것 같습니다.

**Comment by JeMinMoon** [comment]
@merjunemong 내용이 유사한 문서를 합치면서 main에 있던 체크리스트 파일을 의도적으로 지웠습니다. 하지만 체크리스트는 원형 그 상태로 보존하는 편이 좋다고 생각해 따로 branch를 만들어 링크를 걸어뒀습니다. 따라서 현재 main에는 체크리스트가 없는 상태입니다.
