### ISSUE TITLE
논문 내용 분류

### ISSUE THREAD

**Issue by rolling1231** [pwjdgus/Age_Friendly_City#173]
[논문_자료](https://github.com/pwjdgus/Age_Friendly_City/tree/main/%EB%85%BC%EB%AC%B8/%EB%85%BC%EB%AC%B8_%EC%9E%90%EB%A3%8C)를 해외자료와 국내 자료로 분류하여 저장하면 국내의 시각과 해외의 시각을 분리하여 확인할 수 있습니다.

**Comment by wlwhsxz** [comment]
작업 완료했습니다.
