### ISSUE TITLE
독거노인비율 추가

### ISSUE THREAD

**Issue by Dwarf-workroom** [pwjdgus/Age_Friendly_City#180]
고령인들 중 가장 취약할 수 있는 독거노인비율 데이터를 추가하였습니다.

**Comment by JeMinMoon** [comment]
혹시 #162 말씀하신 거라면 conflict때문에 merge가 안 되는 상태이니 확인해주시기 바랍니다.

**Comment by wlwhsxz** [comment]
@Dwarf-workroom 내용 확인 되었나요?
