### ISSUE TITLE
자료 체계화

### ISSUE THREAD

**Issue by klavna** [pwjdgus/Age_Friendly_City#183]
더 좋은 의견있으면 알려주세요
현재 폴더들은 더 상위 개념들과 함께 존재합니다.

예)
   수집 자료 -상위 개념
   논문 - 하위 개념
   데이터 파일 - 하위 개념
따라서 자료 저장이 체계적이지 못해 자료를 찾고 추가하는데, 많은 어려움이 있습니다.
 그래서 폴더들의 위치를 변경하려합니다
정책자료  (국내 자료, 해외 자료)
사례          (국내 사례, 해외 사례)
기타 자료  (통계 자료 ,기타 )   
참고 사이트
논문

**Comment by wlwhsxz** [comment]
@klavna 해당 내용 현재 진행된 상태일까요?
