### ISSUE TITLE
readme 파일의 특정부분을 수정했으면 좋겠습니다.

### ISSUE THREAD

**Issue by Telettubi** [pwjdgus/Age_Friendly_City#188]
현재 readme 파일 맨 윗 부분을 보면 
수집현황이라 되어있고 고령친화 도시란? / 고령친화 도시의 건설 이유 등등이 적혀있는데
이는 수집현황이 아닌 고령친화 도시가 왜 필요한지 또는 무엇인지에 대한 설명이라 보는데
그럼 제목을 수집현황이 아닌 다른걸로 바꿔야하지 않을까 싶습니다.

**Comment by sj2305** [comment]
결국엔 고령친화 도시와 관련된 자료를 수집한 것이기 때문에 '수집현황'으로 분류한걸로 보입니다.
제 생각엔 '수집현황' 대신 '개요' 또는 '진행방향' 등으로 바꾸면 좋을 것 같습니다.
