### ISSUE TITLE
고령친화도시 국제네트워크

### ISSUE THREAD

**Issue by Oryuca** [pwjdgus/Age_Friendly_City#191]
자료 수집 현황에 고령친화도시 국제네트워크가 2개의 부분으로  떨어져 있어 하나로 묶으면 좋겠습니다.

**Comment by sj2305** [comment]
저도 동의합니다.
링크걸린 부분을 클릭하면 페이지를 찾을 수 없다고 나오는데 아마도 코드가 잘못된 것으로 보입니다.

**Comment by wlwhsxz** [comment]
@Oryuca @sj2305 해당 내용 해결 됐나요 ? =]

**Comment by sj2305** [comment]
> @Oryuca @sj2305 해당 내용 해결 됐나요 ? =]

네 지금은 잘 보입니다.

**Comment by wlwhsxz** [comment]
네, 그러면 close 하겠습니다 =]
