### ISSUE TITLE
동아시아 나라들의 고령친화산업 정책현황입니다

### ISSUE THREAD

**Issue by BugeonBG** [pwjdgus/Age_Friendly_City#203]
[동아시아 나라들 고령친화산업 정책현황.pdf](https://github.com/pwjdgus/Age_Friendly_City/files/8499763/default.pdf)

해외사례들 적을 때 쓰면 좋을 듯 합니다.

**Comment by wlwhsxz** [comment]
[참고자료](file:///C:/Users/Minu/Downloads/default%20(1).pdf)
