### ISSUE TITLE
자료 수집 및 분류 가이드라인

### ISSUE THREAD

**Issue by wlwhsxz** [pwjdgus/Age_Friendly_City#206]
**Description**
[예시](https://github.com/pwjdgus/Age_Friendly_City/blob/main/%EB%85%BC%EB%AC%B8/%EC%9E%90%EB%A3%8C%EC%B6%94%EA%B0%80%20%EC%A0%84%20%ED%95%84%EB%8F%85.md)
해당 자료와 같이 각 폴더를 설명하고 개략적인 형식을 지침 하는 파일이 있었으면 좋겠습니다 ^^

**Comment by wlwhsxz** [comment]
@JeMinMoon 기여자님 내용 예시로 wiki에 자료 수집 및 분류 시 가이드라인 항목으로 추가하도록 하겠습니다.
wiki 페이지()에서 확인 가능합니다.
내용 수정 필요하시면 변경 후 피드백 부탁 드립니다 =]

**Comment by JeMinMoon** [comment]
내용 수정을 필요 없을 것 같고 깔끔하게 정리를 잘 하셨네요. 일찍 가이드라인이 만들어졌다면 좋았을 것 같은데 아쉽습니다.

**Comment by wlwhsxz** [comment]
@JeMinMoon 감사합니다. 동감하는 부분입니다 ㅠㅠ
해당 이슈는 close 하도록 하겠습니다.
