### ISSUE TITLE
Readme 파일 구성방향

### ISSUE THREAD

**Issue by Roniebin** [pwjdgus/Age_Friendly_City#213]
Readme는 필요한 정보를 한번에 빠르게 캐치 할 수있게 만들어야합니다. 따라서 간단명료해야하며, 꼭필요한 내용만 넣는것이 좋을것 같습니다. 파일안에 자료가있는 중복된 내용은 제거하는것이 좋을것 같습니다

**Comment by sj2305** [comment]
동의합니다.
