### ISSUE TITLE
Wiki 활용

### ISSUE THREAD

**Issue by wlwhsxz** [pwjdgus/Age_Friendly_City#216]
**Description**
```
생소하거나 전문적인 용어들은 wiki 에 정리하면 좋을 듯 합니다.
현재는 고령친화도시와 고령친화도시 국제네트워크에 관한 wiki 만 정리되어 있어 앞으로 할 일이 많을 듯 합니다 ! 
```

**Comment by sj2305** [comment]
저도 그렇게 생각합니다.
다른 저장소들도 그렇게 진행되고 있는 상황입니다.

**Comment by wlwhsxz** [comment]
> 저도 그렇게 생각합니다. 다른 저장소들도 그렇게 진행되고 있는 상황입니다.

위키에 자세한 내용들과 통계 자료들을 보여주는 링크들을 첨부하고 메인에 보여지는 README.md 파일에서는 최대한 간단하게 만드는 편이 좋다고 생각하여 수정한 것을 pull request 해 놓은 상태입니다.
