### ISSUE TITLE
md파일 삭제 제안

### ISSUE THREAD

**Issue by sj2305** [pwjdgus/Age_Friendly_City#221]
CODE_OF_CONDUCT.md
CONTRIBUTING.md

위 두 파일엔 '고령친화도시'와 전혀 관련없는 내용이 들어가있어서 삭제하는게 좋을것 같다고 생각합니다.

**Comment by Auint** [comment]
확인하였습니다.

1. CODE_OF_CONDUCT.md와 같이 규칙 혹은 지침을 지정하거나 생성할 경우에는 개인이 혼자 하기보다 issue와 같이 여러 사람들이 의논할 수 있게 하여 수정하는 부분이 중요합니다. 따라서 사전에 논의되지 않은 이 부분은 삭제를 진행하거나 논의를 새로 열어서 진행하면 될 것 같습니다.

2. CONTRIBUTING.md에서 이어지는 how to Contribute와 같은 부분은 작성하면 좋은 부분이긴 합니다.
다만 이 부분은 말씀해 주신 것처럼 파일상에 위치하는 것보다 README같은 정리파일에 wiki링크를 걸어두는 것이 좋겠습니다.

@wlwhsxz
수고하셨습니다.

**Comment by wlwhsxz** [comment]
@sj2305 @Auint 말씀 감사합니다. 내용대로 수정하겠습니다 ^^
