### ISSUE TITLE
README 파일 수정

### ISSUE THREAD

**Issue by 0406ckh** [pwjdgus/Age_Friendly_City#223]
main의 README 파일에 v1.2.0-alpha README 파일을 가져오는 것이 좋을 것 같습니다.

**Comment by sj2305** [comment]
노인인구 증가추이 파일은 이미 수집자료 폴더안에 들어가있기 때문에 그대로 두면 되고
관련논문사이트 파일만 논문 폴더로 옮기면 될 것 같습니다.

**Comment by wlwhsxz** [comment]
@0406ckh @sj2305 해당 이슈 진행 확인으로 close 하겠습니다
