### ISSUE TITLE
프로젝트 활동 저조

### ISSUE THREAD

**Issue by wlwhsxz** [pwjdgus/Age_Friendly_City#227]
```
학생들의 활동이 중간고사를 기점으로 없어졌네요.
저는 주로 다른 학생들이 올린 내용을 리뷰하고 수정하고 폴더 관리를 하곤 했었는데 제가 할 일이 없어졌습니다.
```

**Comment by pwjdgus** [comment]
> 저는 주로 다른 학생들이 올린 내용을 리뷰하고 수정하고 폴더 관리를 하곤 했었는데 제가 할 일이 없어졌습니다.

이외 다른 방법으로 프로젝트에 기여할 방법은 많다고 생각합니다.

ex) 기존에 다른 학생들이 하던 방법

**Comment by wlwhsxz** [comment]
@pwjdgus 답변 감사합니다 ^^ 다른 학생들이 하던 방법 참고해서 이어나가겠습니다
