### ISSUE TITLE
보기 편하도록 동일한 주제일 경우에는 한 폴더에 모아놓으면 좋겠습니다.

### ISSUE THREAD

**Issue by Donghan1** [pwjdgus/Age_Friendly_City#249]
많은 사람들이 issue를 생성하기 때문에 동일한 주제일 경우에는 하나의 파일에 의견들을 모아서 정리해둔다면 보기 편리할 것 같습니다.

**Comment by wlwhsxz** [comment]
해당 내용 반영하여 pull request 진행하였습니다.
확인 후, 피드백 남겨주시면 감사하겠습니다 =]

**Comment by Donghan1** [comment]
확인했습니다!

**Comment by wlwhsxz** [comment]
@Donghan1 해당 이슈 close 진행하겠습니다.
