### ISSUE TITLE
WHO 고령친화도시 가이드 및 체크리스트.md파일 삭제관련질문

### ISSUE THREAD

**Issue by Roniebin** [pwjdgus/Age_Friendly_City#251]
@rolling1231 pull request하는 과정에서 파일이 갑자기 삭제되어 conflict가 났는데 혹시 파일을 삭제한 이유가있는지 궁금합니다.

**Comment by rolling1231** [comment]
고령친화도시에 대한 내용이 중복되어있어 삭제하였습니다.

**Comment by Roniebin** [comment]
넵 확인했습니다.
