### ISSUE TITLE
국가지표체계에서 찾은 그래프 자료 업로드 형식에 대해

### ISSUE THREAD

**Issue by merjunemong** [pwjdgus/Age_Friendly_City#255]
국가지표체계라는 사이트에서 그래프/통계표 형태의 자료를 찾았습니다. 현재 #242 로 merge를 요청해놓은 상태이며, 현재 링크만 걸어 둔 상태입니다. 추후에 폴더를 하나 만들어 이 자료를 링크를 안 타고 들어가도 이 저장소에서 바로 볼 수 있게 자료를 입력하려 하는데, 그 중 그래프에 마우스 커서를 올리면 자세히 수치가 나오는데 이 기능을 이 저장소에 그대로 구현할 수 있는 방법이 있을까요?
아니면 이런 기능은 사이트 들어가서 할 수 있게 하고 그래프 사진만 올려두는게 더 보기 좋을까요?
![image](https://user-images.githubusercontent.com/100757595/170815190-2b473200-2034-487e-af7e-89f1c156ab48.png)

**Comment by wlwhsxz** [comment]
저희 저장소에서 보여줄 수 있는 대표적인 예시를 보여주고
자세한 내용은 해당 페이지에서 직접 확인할 수 있도록 하는 방안이 더 효과적일 듯 합니다 =]
