### ISSUE TITLE
노인복지 생활시설 수 & 생활현황 통계자료(2014~2020)

### ISSUE THREAD

**Issue by sj2305** [pwjdgus/Age_Friendly_City#256]
2014년부터 2020년까지의 노인복지 생활시설 수 & 생활현황 자료를 가져와봤습니다.

출처 : Kosis 국가통계포털
https://kosis.kr/statHtml/statHtml.do?orgId=117&tblId=DT_117N_B00003

[노인복지_생활시설_수_및_생활현황_20220526092046.xlsx](https://github.com/pwjdgus/Age_Friendly_City/files/8790794/_._._._._20220526092046.xlsx)

**Comment by wlwhsxz** [comment]
해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤,
어떤 방향으로 사용 될지 제시하며 파일으로 pull request를 하는 것이 더 바람직해 보입니다.

**Comment by sj2305** [comment]
> 해당 자료들은 Issues 에 등록되기 보다 개인 branch 에 자료를 모아 정리한 뒤, 어떤 방향으로 사용 될지 제시하며 파일으로 pull request를 하는 것이 더 바람직해 보입니다.

자세히 확인해본 결과 'Age_Friendly_City/수집 자료/데이터 셋/노인복지시설현황/'노인복지시설 현황.csv' 파일에
동일한 내용이 있는 것으로 확인됐는데 해당 파일의 년도 범위는 2017년부터 2020년까지이고

제가 제시한 파일은 2014년부터 2020년도까지입니다.
범위가 넓은만큼 통계표와 내용이 매우 복잡하게 구성되어 있어서

간소화 된 현재 파일을 그냥 그대로 두는 것이 좋을 것 같습니다.

**Comment by wlwhsxz** [comment]
@sj2305 확인하였습니다 =] 
의견 감사드립니다.
해당 이슈 close 하도록 하겠습니다.
