### ISSUE TITLE
고려 제안: 수집자료들을 위키에 제안

### ISSUE THREAD

**Issue by CECode** [pwjdgus/Age_Friendly_City#264]
그 수집 자료를 들어가보았을 때 너무 수집 자료가 많다시피 하여 하나하나 
들어가보기가 힘드다보니 따로 위키에 new page하나 만들어서 거기에 수집자료를 나열하는 의견을 제안해봅니다.

**Comment by wlwhsxz** [comment]
혹은 폴더명을 기타 자료로 변경한 뒤, 필요한 파일 - 필요치 않은 파일로 재 분류함은 어떨까요?
현재 존재하는 자료들 대부분 적합한 pull requests - merge  과정 없이 main 에 직접 commit 되었던 터라, 
다소 data chunk 들만 덩그러니 있는 듯 합니다.

이에, 기존 자료 재 분류 및 정리 혹은 삭제 과정이 필요하다 생각이 됩니다.

**Comment by CECode** [comment]
알겠습니다.
