### ISSUE TITLE
고령화로 인한 피해

### ISSUE THREAD

**Issue by Donghan1** [pwjdgus/Age_Friendly_City#268]
- 경제적 성장 침제
 1. 고령화 사회로 인해 고령층이 생산 활동에 참여하지 않는 수가 늘어나면서 비생산 영역에 자본이 투입되는 상황이 늘어나 경제 성장이 억제되는 현상이 발생할 수 있습니다. 
 
- 노인 부양에 대한 부담감 증대
 1. 고령화 사회로 인해서 연금을 받고자 하는 인구가 증가하여 재정에 있어 큰 부담감을 느낄 수 있습니다.
 2. 젊음 층의 세대와 갈등이 발생해 고령화 인구가 사회적 소외 집단으로 변화 할 수 있습니다.

- 노인 복지 서비스 문제
 1.  고령화 인구의 증가로 보호소, 요양원 등 노인을 위한 시설이 증가해야 하므로  재정적으로 큰 부담이 올 수 있습니다.

- 의료영역 자본 문제
 1. 고령화 인구 증가로 인해 국민의료 보험을 지원받고자 하는 대상의 수가 늘어나 재정적 영역에서 큰 부담이 발생할 수 있습니다.

**Comment by wlwhsxz** [comment]
앞선 이슈와 마찬가지로,

해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤, 
어떤 방향으로 사용 될지 제시하며 파일으로써 pull request를 하는 것이 더 바람직해 보입니다.

**Comment by Donghan1** [comment]
네!

**Comment by wlwhsxz** [comment]
@Donghan1 해당 이슈 close 하도록 하겠습니다 =]
