### ISSUE TITLE
고령화가 왜 심각해지는지에 대한 자료가 추가 제안

### ISSUE THREAD

**Issue by CECode** [pwjdgus/Age_Friendly_City#274]
노인이나 사회적 약자들에게 중시한 현황이나 정책들만 있다보니
왜 고령화가 가속화가 되는 것인지 심각성이 어느정도인지에 대한 설명 및 시각적 그래프가 있으면
좋겠습니다.

**Comment by wlwhsxz** [comment]
이슈 작성에 관한
[기여 가이드라인](https://github.com/pwjdgus/Age_Friendly_City/wiki/Contribution-Guidelines) 참고 후 수정해주시면 감사하겠습니다 =]

또한, 해당 자료들은 Issues 에 등록되기 보다
개인 branch 에 자료를 모아 정리한 뒤,
어떤 방향으로 사용 될지 제시하며 파일으로 pull request를 하는 것이 더 바람직해 보입니다.
