### ISSUE TITLE
파일 위치 이동 제안

### ISSUE THREAD

**Issue by CECode** [pwjdgus/Age_Friendly_City#275]
그 개인적으로 간단한 고령인구로 통한 현황 및 출처가 있으므로
수집 자료에 있는 "우리나라 고령인구 증가율.md"를 수집 자료/인구 관련자료에 넣는 것이 좋아보입니다.

**Comment by wlwhsxz** [comment]
이슈 작성에 관한
[기여 가이드라인](https://github.com/pwjdgus/Age_Friendly_City/wiki/Contribution-Guidelines) 참고 바랍니다.
