### ISSUE TITLE
해외사례 조사

### ISSUE THREAD

**Issue by wlwhsxz** [pwjdgus/Age_Friendly_City#57]
해외사례들을 조사 하게 되면 이 정보들은 한글로 옮겨야 될까요?

**Comment by pwjdgus** [comment]
한글로 옮기면 의미에 대해 약간의 차이가 발생할 수 있으니 영어로 올려주세요 ^^

**Comment by wlwhsxz** [comment]
네, 확인했습니다. 감사합니다 =]
