### ISSUE TITLE
고령친화 식품내용의 필요성

### ISSUE THREAD

**Issue by Roniebin** [pwjdgus/Age_Friendly_City#76]
고령친화식품 내용을 읽어본후, 고령친화 도시개발과 연관성이 있는지 잘이해하지 못했습니다. 혹시 연관이 있다면 어떤 내용인지 설명부탁드립니다.

**Comment by hjun0325** [comment]
고령친화도시는 노인이 건강하고 활력있는 사회생활을 영위할 수 있도록 정책 및 인프라, 서비스 등이 조성된 도시를 말합니다.
그래서 저는 고령친화식품은 노인들의 건강을 위한 서비스부분에 해당한다고 생각해서 추가했습니다.
