### ISSUE TITLE
고령에 대한 세부적인 정책자료를 추가하면 좋겠습니다.

### ISSUE THREAD

**Issue by sangyong-99** [pwjdgus/Age_Friendly_City#84]
고령에 대한 세부적인 정책자료를 추가하면 좋겠습니다.

**Comment by JeMinMoon** [comment]
동의합니다. 정책자료.md에 추가해나가면 될 것 같습니다.

**Comment by wlwhsxz** [comment]
해당 건 자료 추가 되었을까요? @sangyong-99 @JeMinMoon
